name: sites_platform
channels:
  - conda-forge

dependencies:
  - vim=8.2
  - cmake
  - compilers
  - gcc_linux-64
  - gdal
  - cdo>=1.9.7
  - eccodes!=2.19.0  # cdo dependency; something messed up with libeccodes.so
  - mpich<3.4  # avoid 3.4.1 external_2 from conda-forge like the plague
  - nco
  - ncl>=6.5.0  # this should always install 6.6.0 though
  - python=3.8
  - pip
  - ipdb=0.13
  - pandas=1.2
